Add missing library dependency.
Fixes the following link error in SANITIZE_TARGET=address build for
hammerhead:
system/bt/audio_a2dp_hw/audio_a2dp_hw.c:208: error: undefined reference
to 'osi_socket_local_client_connect'

Bug: 21785137
Change-Id: Ie29a2772e7f1a4f697d895eb29b01d39d6f9c651