Fix build error caused by missing LOG_TAG
FAILED: gcc -MMD -MF obj/hci/src/libhci.hci_packet_parser.o.d -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -DHAS_NO_BDROID_BUILDCFG -DLOG_NDEBUG=1 -DEXPORT_SYMBOL=__attribute__\(\(visibility\(\"default\"\)\)\) -DKERNEL_MISSING_CLOCK_BOOTTIME_ALARM=TRUE -DOS_GENERIC -I../../hci/include -I../.. -I../../include -I../../bta/include -I../../btcore/include -I../../stack/include -I/home/patrick/src/fluoride/libhardware/include -I/home/patrick/src/fluoride/core/include -I/home/patrick/src/fluoride/media/audio/include -g -O0 -fpic -fdata-sections -ffunction-sections -fvisibility=hidden -std=c99 -c ../../hci/src/hci_packet_parser.c -o obj/hci/src/libhci.hci_packet_parser.o
In file included from ../../hci/src/hci_packet_parser.c:28:0:
../../hci/src/hci_packet_parser.c: In function ‘read_command_complete_header’:
../../hci/src/hci_packet_parser.c:239:43: error: expected ‘)’ before ‘__func__’
     LOG_ERROR("%s: return status - 0x%x", __func__, status);

Change-Id: I6ca721ba24ba3170d701f606f0676c5c4e707cf8