Fix a Qualcomm format string.
hardware/qcom/wlan/qcwcn/wifi_hal/wifilogger.cpp:1073:37: error: data argument not used by format string [-Werror,-Wformat-extra-args]
                      "size of %d", __func__, memDumpSize);
                                    ^
Interestingly, this shows that we actually have a bug in the error detection
in log.h --- we didn't complain about this code until there were *two* unused
arguments.

Change-Id: Id332c10e1a67fd17e7f2cbefc8ef60203986cc4f
(cherry picked from commit 6c7afa806a3d73a8bb3950583abc23ba012a2c4f)